include $(src)/Makefile.header-test # Extra header tests

i915-y += \
	i915_gem_busy.o \
	i915_gem_clflush.o \
	i915_gem_client_blt.o \
	i915_gem_context.o \
	i915_gem_dmabuf.o \
	i915_gem_domain.o \
	i915_gem_execbuffer.o \
	i915_gem_fence.o \
	i915_gem_internal.o \
	i915_gem_object.o \
	i915_gem_object_blt.o \
	i915_gem_mman.o \
	i915_gem_pages.o \
	i915_gem_phys.o \
	i915_gem_pm.o \
	i915_gem_shmem.o \
	i915_gem_shrinker.o \
	i915_gem_stolen.o \
	i915_gem_throttle.o \
	i915_gem_tiling.o \
	i915_gem_userptr.o \
	i915_gem_wait.o \
	i915_gemfs.o

i915-$(CONFIG_DRM_I915_SELFTEST) += selftests/
